services:
  object_effects:
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    ports:
      - 5610:80
    env_file:
      - .env.production
    volumes:
      - /var/essdata/popframe_cache:/__cache__
    restart: always

